version: '3.8'
services:
  alwrity:
    build:
      context: ../..
      dockerfile: Getting Started/Option_3_Docker_Install/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_TELEMETRY=0
    volumes:
      - ../../.env:/app/.env
    restart: unless-stopped
